import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

// importing components
import Navbar from "../components/Navbar";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className=" bg-bgcolor w-full  font-poppins">
        <Navbar />
        <Header />
      </main>
    </>
  );
}
